---
- hosts: all                                                                                                                         
  become: true                                                                                                                         
  tasks:                  
    - name: install security patches
      ansible.builtin.dnf:                                                                                                                   
        name: "{{ item }}"                                                                                                                
        state: latest                                                                                                                       
      loop:                                                                                                                               
        - openssh                                                                                                                         
        - openssl    
      ignore_errors: yes
    - name: check docker version
      ansible.builtin.command: docker --version
      register: output
      ignore_errors: yes
    - ansible.builtin.debug:
        var: output
    - name: install docker
      ansible.builtin.dnf:
        name: docker
        state: present
      #when: output.failed
    - name: check file exist or not
      ansible.builtin.command:
        name: ls /etc/docker
      register: result
      failed_when:
       # - result.rc == 0
        - '"No such" not in result.stdout'
