---
- hosts: localhost
  connection: local
  tasks:
  - name: Create  Ec2 instancies
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "New-SSH-Key"
      instance_type: t2.micro
      security_group: default
      region: ap-south-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
    loop:
     - { image: "ami-0144277607031eca2" , name: "mg-node1" }
     - { image: "ami-0144277607031eca2" , name: "mg-node2" }
     - { image: "ami-0f918f7e67a3323f0" , name: "mg-node3" }
