---
- hosts: webservers                                                                                                                         
  become: true                                                                                                                              
  becom_user: root                                                                                                                          
  tasks:                  
    - name: install security patches                                                                                                                      - name: install security updates
      ansible.builtin.dnf:                                                                                                                   
        name: "{{ iteam}}"                                                                                                                
        state: latest                                                                                                                       
      loop:                                                                                                                               
        - openssh                                                                                                                         
        - openssl    
      #ignore_errors: yes
    - name: check docker version
      ansible.builtin.command: docker --version
      register: output
      ignore_errors: yes
    - ansible.builtin.debug:
        var: output
    - name: install docker
      ansible.builtin.dnf:
        name: docker.io
        state: present
      when: output.failed
